#ifndef _MAPSERVER_VERSION_H
#define _MAPSERVER_VERSION_H

#define MS_VERSION_MAJOR 7
#define MS_VERSION_MINOR 6
#define MS_VERSION_REV 4
#define MS_VERSION "7.6.4"
#define MS_VERSION_NUM  70604 

#endif

